apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: development
  labels:
    app: nginx-test
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http